/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author Cesar
 */
public class VServicio extends javax.swing.JFrame {

    /**
     * Creates new form VServicio2
     */
    public VServicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(VServicio.DO_NOTHING_ON_CLOSE); // bloquear el boton cerrar
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDesdeA = new javax.swing.JTextField();
        txtHastaA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPEC = new javax.swing.JTextField();
        txtDesdeC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHastaC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtPEA = new javax.swing.JTextField();
        txtDesdeT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtHastaT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPET = new javax.swing.JTextField();
        txtSeguroT = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtDesdeE = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtHastaE = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtLugarE = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtSeguroE = new javax.swing.JTextField();
        txtPEE = new javax.swing.JTextField();
        botonACEPTAR = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        botonAgregarA = new javax.swing.JButton();
        botonAgregarC = new javax.swing.JButton();
        botonAgregarT = new javax.swing.JButton();
        botonAgregarE = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        botonACEPTAR1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBox1.setText("Alojamiento");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Comida");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Transporte");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Excursion");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Desde:");

        jLabel2.setText("Hasta:");

        txtDesdeA.setEnabled(false);
        txtDesdeA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDesdeAKeyTyped(evt);
            }
        });

        txtHastaA.setEnabled(false);
        txtHastaA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHastaAKeyTyped(evt);
            }
        });

        jLabel3.setText("Categoria:");

        jRadioButton1.setText("*");
        jRadioButton1.setEnabled(false);

        jRadioButton2.setText("**");
        jRadioButton2.setEnabled(false);

        jRadioButton3.setText("***");
        jRadioButton3.setEnabled(false);

        jRadioButton4.setText("****");
        jRadioButton4.setEnabled(false);

        jRadioButton5.setText("*****");
        jRadioButton5.setEnabled(false);

        jLabel4.setText("Ciudad:");

        jLabel5.setText("Precio Especial:");

        txtPEC.setEnabled(false);
        txtPEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPECActionPerformed(evt);
            }
        });
        txtPEC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPECKeyTyped(evt);
            }
        });

        txtDesdeC.setEnabled(false);
        txtDesdeC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDesdeCKeyTyped(evt);
            }
        });

        jLabel6.setText("Desde:");

        jLabel7.setText("Hasta:");

        txtHastaC.setEnabled(false);
        txtHastaC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHastaCKeyTyped(evt);
            }
        });

        jLabel8.setText("Tipo:");

        jRadioButton6.setText("Desayuno");
        jRadioButton6.setEnabled(false);
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.setText("Almuerzo");
        jRadioButton7.setEnabled(false);

        jRadioButton8.setText("Merienda");
        jRadioButton8.setEnabled(false);

        jRadioButton9.setText("Cena");
        jRadioButton9.setEnabled(false);

        jLabel9.setText("Precio Especial:");

        txtPEA.setEnabled(false);
        txtPEA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPEAKeyTyped(evt);
            }
        });

        txtDesdeT.setEnabled(false);
        txtDesdeT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDesdeTKeyTyped(evt);
            }
        });

        jLabel10.setText("Desde:");

        jLabel11.setText("Hasta:");

        txtHastaT.setEnabled(false);
        txtHastaT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHastaTKeyTyped(evt);
            }
        });

        jLabel12.setText("Tipo de Vehiculo:");

        jRadioButton10.setText("Omnibus");
        jRadioButton10.setEnabled(false);

        jRadioButton11.setText("Avion");
        jRadioButton11.setEnabled(false);

        jLabel13.setText("Comodidad:");

        jRadioButton12.setText("Basico");
        jRadioButton12.setEnabled(false);

        jRadioButton13.setText("Ejecutivo");
        jRadioButton13.setEnabled(false);

        jLabel14.setText("Seguro:");

        jLabel15.setText("Precio Especial:");

        txtPET.setEnabled(false);
        txtPET.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPETKeyTyped(evt);
            }
        });

        txtSeguroT.setEnabled(false);
        txtSeguroT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeguroTKeyTyped(evt);
            }
        });

        txtDesdeE.setEnabled(false);
        txtDesdeE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDesdeEKeyTyped(evt);
            }
        });

        jLabel16.setText("Desde:");

        jLabel17.setText("Hasta:");

        txtHastaE.setEnabled(false);
        txtHastaE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHastaEKeyTyped(evt);
            }
        });

        jLabel18.setText("Lugar:");

        txtLugarE.setEnabled(false);

        jLabel19.setText("Precio Especial:");

        jLabel20.setText("Seguro:");

        txtSeguroE.setEnabled(false);
        txtSeguroE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeguroEKeyTyped(evt);
            }
        });

        txtPEE.setEnabled(false);
        txtPEE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPEEKeyTyped(evt);
            }
        });

        botonACEPTAR.setText("CANCELAR");
        botonACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonACEPTARActionPerformed(evt);
            }
        });

        botonAgregarA.setText("Agregar");
        botonAgregarA.setEnabled(false);
        botonAgregarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarAActionPerformed(evt);
            }
        });

        botonAgregarC.setText("Agregar");
        botonAgregarC.setEnabled(false);
        botonAgregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarCActionPerformed(evt);
            }
        });

        botonAgregarT.setText("Agregar");
        botonAgregarT.setEnabled(false);
        botonAgregarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarTActionPerformed(evt);
            }
        });

        botonAgregarE.setText("Agregar");
        botonAgregarE.setEnabled(false);
        botonAgregarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarEActionPerformed(evt);
            }
        });

        jComboBox1.setEnabled(false);

        botonACEPTAR1.setText("ACEPTAR");
        botonACEPTAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonACEPTAR1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .addComponent(botonACEPTAR1)
                .addGap(168, 168, 168)
                .addComponent(botonACEPTAR)
                .addGap(386, 386, 386))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDesdeA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHastaA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDesdeC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHastaC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHastaE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDesdeE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDesdeT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(30, 30, 30)
                        .addComponent(txtHastaT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jCheckBox1)
                            .addGap(43, 43, 43)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(179, 179, 179)
                            .addComponent(jLabel12)
                            .addGap(119, 119, 119)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(jRadioButton8))
                                .addComponent(jRadioButton11))
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButton9)
                            .addGap(59, 59, 59)
                            .addComponent(txtPEA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(940, 940, 940)
                            .addComponent(botonAgregarT))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(670, 670, 670)
                            .addComponent(jLabel19))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jCheckBox4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(390, 390, 390)
                            .addComponent(txtLugarE, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(769, 769, 769)
                            .addComponent(txtPET, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(667, 667, 667)
                            .addComponent(jLabel5))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(509, 509, 509)
                            .addComponent(jRadioButton3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(570, 570, 570)
                            .addComponent(jRadioButton4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(769, 769, 769)
                            .addComponent(txtSeguroT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(335, 335, 335)
                            .addComponent(jLabel8))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(390, 390, 390)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(439, 439, 439)
                            .addComponent(jRadioButton10))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(485, 485, 485)
                            .addComponent(jRadioButton7))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(534, 534, 534)
                            .addComponent(jRadioButton13))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(940, 940, 940)
                            .addComponent(botonAgregarC))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(454, 454, 454)
                            .addComponent(jRadioButton2))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(940, 940, 940)
                            .addComponent(botonAgregarA))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(439, 439, 439)
                            .addComponent(jRadioButton12))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(336, 336, 336)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(770, 770, 770)
                            .addComponent(txtSeguroE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(670, 670, 670)
                            .addComponent(jLabel20))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(769, 769, 769)
                            .addComponent(txtPEC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(669, 669, 669)
                            .addComponent(jLabel14))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(394, 394, 394)
                            .addComponent(jRadioButton6))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(336, 336, 336)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(668, 668, 668)
                            .addComponent(jLabel9))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(940, 940, 940)
                            .addComponent(botonAgregarE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(405, 405, 405)
                            .addComponent(jRadioButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(340, 340, 340)
                            .addComponent(jLabel18))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(637, 637, 637)
                            .addComponent(jRadioButton5))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(770, 770, 770)
                            .addComponent(txtPEE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(669, 669, 669)
                            .addComponent(jLabel15))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jCheckBox3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(332, 332, 332)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jCheckBox2))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesdeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHastaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesdeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHastaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesdeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHastaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesdeE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHastaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonACEPTAR1)
                    .addComponent(botonACEPTAR))
                .addGap(26, 26, 26))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jCheckBox1))
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(268, 268, 268)
                            .addComponent(jLabel12))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(jRadioButton8)
                            .addGap(100, 100, 100)
                            .addComponent(jRadioButton11))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(jRadioButton9))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(txtPEA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(290, 290, 290)
                            .addComponent(botonAgregarT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(440, 440, 440)
                            .addComponent(jLabel19))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(410, 410, 410)
                            .addComponent(jCheckBox4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(390, 390, 390)
                            .addComponent(txtLugarE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(244, 244, 244)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(311, 311, 311)
                            .addComponent(txtPET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(jLabel5))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jRadioButton3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jRadioButton4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(265, 265, 265)
                            .addComponent(txtSeguroT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(145, 145, 145)
                            .addComponent(jLabel8))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(264, 264, 264)
                            .addComponent(jRadioButton10))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(jRadioButton7))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(310, 310, 310)
                            .addComponent(jRadioButton13))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(botonAgregarC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jRadioButton2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(botonAgregarA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(310, 310, 310)
                            .addComponent(jRadioButton12))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(390, 390, 390)
                            .addComponent(txtSeguroE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(390, 390, 390)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(195, 195, 195)
                            .addComponent(txtPEC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(268, 268, 268)
                            .addComponent(jLabel14))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(jRadioButton6))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(198, 198, 198)
                            .addComponent(jLabel9))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(410, 410, 410)
                            .addComponent(botonAgregarE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jRadioButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(390, 390, 390)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jRadioButton5))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(440, 440, 440)
                            .addComponent(txtPEE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(314, 314, 314)
                            .addComponent(jLabel15))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(300, 300, 300)
                            .addComponent(jCheckBox3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(314, 314, 314)
                            .addComponent(jLabel13))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(jCheckBox2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(370, 370, 370)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected())
        {
            jComboBox1.setEnabled(true);
            txtDesdeA.setEnabled(true);
            txtHastaA.setEnabled(true);
            txtPEA.setEnabled(true);
            jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
            jRadioButton3.setEnabled(true);
            jRadioButton4.setEnabled(true);
            jRadioButton5.setEnabled(true);
            botonAgregarA.setEnabled(true);
        }
        else
        {
            jComboBox1.setEnabled(false);
            txtDesdeA.setEnabled(false);
            txtHastaA.setEnabled(false);
            //txtPEA.setEnabled(false);
            jRadioButton1.setEnabled(false);
            jRadioButton2.setEnabled(false);
            jRadioButton3.setEnabled(false);
            jRadioButton4.setEnabled(false);
            jRadioButton5.setEnabled(false);
            botonAgregarA.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(jCheckBox2.isSelected())
        {
            txtDesdeC.setEnabled(true);
            txtHastaC.setEnabled(true);
            txtPEC.setEnabled(true);
            jRadioButton6.setEnabled(true);
            jRadioButton7.setEnabled(true);
            jRadioButton8.setEnabled(true);
            jRadioButton9.setEnabled(true);
            botonAgregarC.setEnabled(true);
        }
        else
        {
            txtDesdeC.setEnabled(false);
            txtHastaC.setEnabled(false);
            txtPEC.setEnabled(false);
            jRadioButton6.setEnabled(false);
            jRadioButton7.setEnabled(false);
            jRadioButton8.setEnabled(false);
            jRadioButton9.setEnabled(false);
            botonAgregarC.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if(jCheckBox3.isSelected())
        {
            txtDesdeT.setEnabled(true);
            txtHastaT.setEnabled(true);
            txtPET.setEnabled(true);
            jRadioButton10.setEnabled(true);
            jRadioButton11.setEnabled(true);
            jRadioButton12.setEnabled(true);
            jRadioButton13.setEnabled(true);
            txtSeguroT.setEnabled(true);
            botonAgregarT.setEnabled(true);
        }
        else
        {
            txtDesdeT.setEnabled(false);
            txtHastaT.setEnabled(false);
            txtPET.setEnabled(false);
            jRadioButton10.setEnabled(false);
            jRadioButton11.setEnabled(false);
            jRadioButton12.setEnabled(false);
            jRadioButton13.setEnabled(false);
            txtSeguroT.setEnabled(false);
            botonAgregarT.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        if(jCheckBox4.isSelected())
        {
            txtDesdeE.setEnabled(true);
            txtHastaE.setEnabled(true);
            txtPEE.setEnabled(true);
            txtLugarE.setEnabled(true);
            txtSeguroE.setEnabled(true);
            botonAgregarE.setEnabled(true);
        }
        else
        {
            txtDesdeE.setEnabled(false);
            txtHastaE.setEnabled(false);
            txtPEE.setEnabled(false);
            txtLugarE.setEnabled(false);
            txtSeguroE.setEnabled(false);
            botonAgregarE.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void txtPECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPECActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void botonACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonACEPTARActionPerformed
        controlador.ControladorServicio.cerrar();
    }//GEN-LAST:event_botonACEPTARActionPerformed

    private void botonAgregarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarAActionPerformed
        controlador.ControladorServicio.agregarAlojamiento();
    }//GEN-LAST:event_botonAgregarAActionPerformed

    private void botonAgregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarCActionPerformed
        controlador.ControladorServicio.agregarComida();
        botonAgregarC.setEnabled(false);
        txtDesdeC.setEnabled(false);
        txtDesdeC.setText("");
        txtHastaC.setEnabled(false);
        txtHastaC.setText("");  
        txtPEC.setEnabled(false);
        txtPEC.setText("");
        jRadioButton6.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton8.setEnabled(false);
        jRadioButton9.setEnabled(false);
        jCheckBox2.setSelected(false);
    }//GEN-LAST:event_botonAgregarCActionPerformed

    private void botonAgregarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarTActionPerformed
        controlador.ControladorServicio.agregarTransporte();
        botonAgregarT.setEnabled(false);
        txtDesdeT.setEnabled(false);
        txtDesdeT.setText("");
        txtHastaT.setEnabled(false);
        txtHastaT.setText("");    
        txtPET.setEnabled(false);
        txtPET.setText("");    
        jRadioButton10.setEnabled(false);
        jRadioButton11.setEnabled(false);
        jRadioButton12.setEnabled(false);
        jRadioButton13.setEnabled(false);
        txtSeguroT.setEnabled(false);
        jCheckBox3.setSelected(false);
        txtDesdeT.setText("");
        txtHastaT.setText("");
        txtHastaT.setText("");

    }//GEN-LAST:event_botonAgregarTActionPerformed

    private void botonAgregarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarEActionPerformed
        controlador.ControladorServicio.agregarExcursion();
        botonAgregarE.setEnabled(false);
        txtDesdeE.setEnabled(false);
        txtDesdeE.setText("");
        txtHastaE.setEnabled(false);
        txtHastaE.setText("");
        txtPEE.setEnabled(false);
        txtPEE.setText("");
        txtLugarE.setEnabled(false);
        txtLugarE.setText("");
        txtSeguroE.setEnabled(false);
        txtSeguroE.setText("");
        jCheckBox4.setSelected(false);
    }//GEN-LAST:event_botonAgregarEActionPerformed

    private void botonACEPTAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonACEPTAR1ActionPerformed
        controlador.ControladorServicio.cerrar();
    }//GEN-LAST:event_botonACEPTAR1ActionPerformed

    private void txtDesdeAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDesdeAKeyTyped
        // VALIDAR INGRESO NUMERICO 
        //event--> key---> keytiped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"Solo debe ingresar valores numericos");
        }
    }//GEN-LAST:event_txtDesdeAKeyTyped

    private void txtHastaAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHastaAKeyTyped
         // VALIDAR INGRESO NUMERICO 
        //event--> key---> keytiped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"Solo debe ingresar valores numericos");
        }
    }//GEN-LAST:event_txtHastaAKeyTyped

    private void txtPEAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPEAKeyTyped
         // VALIDAR INGRESO NUMERICO 
        //event--> key---> keytiped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"Solo debe ingresar valores numericos");
        }
    }//GEN-LAST:event_txtPEAKeyTyped

    private void txtDesdeCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDesdeCKeyTyped
        // VALIDAR INGRESO NUMERICO 
        //event--> key---> keytiped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"Solo debe ingresar valores numericos");
        }
    }//GEN-LAST:event_txtDesdeCKeyTyped

    private void txtHastaCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHastaCKeyTyped
         // VALIDAR INGRESO NUMERICO 
        //event--> key---> keytiped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"Solo debe ingresar valores numericos");
        }
    }//GEN-LAST:event_txtHastaCKeyTyped

    private void txtDesdeTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDesdeTKeyTyped
         // VALIDAR INGRESO NUMERICO 
        //event--> key---> keytiped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"Solo debe ingresar valores numericos");
        }
    }//GEN-LAST:event_txtDesdeTKeyTyped

    private void txtHastaTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHastaTKeyTyped
         // VALIDAR INGRESO NUMERICO 
        //event--> key---> keytiped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"Solo debe ingresar valores numericos");
        }
    }//GEN-LAST:event_txtHastaTKeyTyped

    private void txtDesdeEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDesdeEKeyTyped
         // VALIDAR INGRESO NUMERICO 
        //event--> key---> keytiped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"Solo debe ingresar valores numericos");
        }
    }//GEN-LAST:event_txtDesdeEKeyTyped

    private void txtHastaEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHastaEKeyTyped
         // VALIDAR INGRESO NUMERICO 
        //event--> key---> keytiped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"Solo debe ingresar valores numericos");
        }
    }//GEN-LAST:event_txtHastaEKeyTyped

    private void txtPECKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPECKeyTyped
         // VALIDAR INGRESO NUMERICO 
        //event--> key---> keytiped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"Solo debe ingresar valores numericos");
        }
    }//GEN-LAST:event_txtPECKeyTyped

    private void txtSeguroTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeguroTKeyTyped
         // VALIDAR INGRESO NUMERICO 
        //event--> key---> keytiped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"Solo debe ingresar valores numericos");
        }
    }//GEN-LAST:event_txtSeguroTKeyTyped

    private void txtPETKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPETKeyTyped
         // VALIDAR INGRESO NUMERICO 
        //event--> key---> keytiped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"Solo debe ingresar valores numericos");
        }
    }//GEN-LAST:event_txtPETKeyTyped

    private void txtSeguroEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeguroEKeyTyped
         // VALIDAR INGRESO NUMERICO 
        //event--> key---> keytiped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"Solo debe ingresar valores numericos");
        }
    }//GEN-LAST:event_txtSeguroEKeyTyped

    private void txtPEEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPEEKeyTyped
         // VALIDAR INGRESO NUMERICO 
        //event--> key---> keytiped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"Solo debe ingresar valores numericos");
        }
    }//GEN-LAST:event_txtPEEKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonACEPTAR;
    private javax.swing.JButton botonACEPTAR1;
    private javax.swing.JButton botonAgregarA;
    private javax.swing.JButton botonAgregarC;
    private javax.swing.JButton botonAgregarE;
    private javax.swing.JButton botonAgregarT;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField txtDesdeA;
    private javax.swing.JTextField txtDesdeC;
    private javax.swing.JTextField txtDesdeE;
    private javax.swing.JTextField txtDesdeT;
    private javax.swing.JTextField txtHastaA;
    private javax.swing.JTextField txtHastaC;
    private javax.swing.JTextField txtHastaE;
    private javax.swing.JTextField txtHastaT;
    private javax.swing.JTextField txtLugarE;
    private javax.swing.JTextField txtPEA;
    private javax.swing.JTextField txtPEC;
    private javax.swing.JTextField txtPEE;
    private javax.swing.JTextField txtPET;
    private javax.swing.JTextField txtSeguroE;
    private javax.swing.JTextField txtSeguroT;
    // End of variables declaration//GEN-END:variables

    public JButton getBotonACEPTAR() {
        return botonACEPTAR;
    }

    public void setBotonACEPTAR(JButton botonACEPTAR) {
        this.botonACEPTAR = botonACEPTAR;
    }

    public JButton getBotonAgregarA() {
        return botonAgregarA;
    }

    public void setBotonAgregarA(JButton botonAgregarA) {
        this.botonAgregarA = botonAgregarA;
    }

    public JButton getBotonAgregarC() {
        return botonAgregarC;
    }

    public void setBotonAgregarC(JButton botonAgregarC) {
        this.botonAgregarC = botonAgregarC;
    }

    public JButton getBotonAgregarE() {
        return botonAgregarE;
    }

    public void setBotonAgregarE(JButton botonAgregarE) {
        this.botonAgregarE = botonAgregarE;
    }

    public JButton getBotonAgregarT() {
        return botonAgregarT;
    }

    public void setBotonAgregarT(JButton botonAgregarT) {
        this.botonAgregarT = botonAgregarT;
    }

    public JCheckBox getjCheckBox1() {
        return jCheckBox1;
    }

    public void setjCheckBox1(JCheckBox jCheckBox1) {
        this.jCheckBox1 = jCheckBox1;
    }

    public JCheckBox getjCheckBox2() {
        return jCheckBox2;
    }

    public void setjCheckBox2(JCheckBox jCheckBox2) {
        this.jCheckBox2 = jCheckBox2;
    }

    public JCheckBox getjCheckBox3() {
        return jCheckBox3;
    }

    public void setjCheckBox3(JCheckBox jCheckBox3) {
        this.jCheckBox3 = jCheckBox3;
    }

    public JCheckBox getjCheckBox4() {
        return jCheckBox4;
    }

    public void setjCheckBox4(JCheckBox jCheckBox4) {
        this.jCheckBox4 = jCheckBox4;
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public void setjLabel18(JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel20() {
        return jLabel20;
    }

    public void setjLabel20(JLabel jLabel20) {
        this.jLabel20 = jLabel20;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JRadioButton getjRadioButton1() {
        return jRadioButton1;
    }

    public void setjRadioButton1(JRadioButton jRadioButton1) {
        this.jRadioButton1 = jRadioButton1;
    }

    public JRadioButton getjRadioButton10() {
        return jRadioButton10;
    }

    public void setjRadioButton10(JRadioButton jRadioButton10) {
        this.jRadioButton10 = jRadioButton10;
    }

    public JRadioButton getjRadioButton11() {
        return jRadioButton11;
    }

    public void setjRadioButton11(JRadioButton jRadioButton11) {
        this.jRadioButton11 = jRadioButton11;
    }

    public JRadioButton getjRadioButton12() {
        return jRadioButton12;
    }

    public void setjRadioButton12(JRadioButton jRadioButton12) {
        this.jRadioButton12 = jRadioButton12;
    }

    public JRadioButton getjRadioButton13() {
        return jRadioButton13;
    }

    public void setjRadioButton13(JRadioButton jRadioButton13) {
        this.jRadioButton13 = jRadioButton13;
    }

    public JRadioButton getjRadioButton2() {
        return jRadioButton2;
    }

    public void setjRadioButton2(JRadioButton jRadioButton2) {
        this.jRadioButton2 = jRadioButton2;
    }

    public JRadioButton getjRadioButton3() {
        return jRadioButton3;
    }

    public void setjRadioButton3(JRadioButton jRadioButton3) {
        this.jRadioButton3 = jRadioButton3;
    }

    public JRadioButton getjRadioButton4() {
        return jRadioButton4;
    }

    public void setjRadioButton4(JRadioButton jRadioButton4) {
        this.jRadioButton4 = jRadioButton4;
    }

    public JRadioButton getjRadioButton5() {
        return jRadioButton5;
    }

    public void setjRadioButton5(JRadioButton jRadioButton5) {
        this.jRadioButton5 = jRadioButton5;
    }

    public JRadioButton getjRadioButton6() {
        return jRadioButton6;
    }

    public void setjRadioButton6(JRadioButton jRadioButton6) {
        this.jRadioButton6 = jRadioButton6;
    }

    public JRadioButton getjRadioButton7() {
        return jRadioButton7;
    }

    public void setjRadioButton7(JRadioButton jRadioButton7) {
        this.jRadioButton7 = jRadioButton7;
    }

    public JRadioButton getjRadioButton8() {
        return jRadioButton8;
    }

    public void setjRadioButton8(JRadioButton jRadioButton8) {
        this.jRadioButton8 = jRadioButton8;
    }

    public JRadioButton getjRadioButton9() {
        return jRadioButton9;
    }

    public void setjRadioButton9(JRadioButton jRadioButton9) {
        this.jRadioButton9 = jRadioButton9;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JSeparator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JSeparator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JSeparator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JSeparator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JSeparator getjSeparator4() {
        return jSeparator4;
    }

    public void setjSeparator4(JSeparator jSeparator4) {
        this.jSeparator4 = jSeparator4;
    }

    public JSeparator getjSeparator5() {
        return jSeparator5;
    }

    public void setjSeparator5(JSeparator jSeparator5) {
        this.jSeparator5 = jSeparator5;
    }

    public JSeparator getjSeparator6() {
        return jSeparator6;
    }

    public void setjSeparator6(JSeparator jSeparator6) {
        this.jSeparator6 = jSeparator6;
    }

    public JSeparator getjSeparator7() {
        return jSeparator7;
    }

    public void setjSeparator7(JSeparator jSeparator7) {
        this.jSeparator7 = jSeparator7;
    }

    public JTextField getTxtDesdeA() {
        return txtDesdeA;
    }

    public void setTxtDesdeA(JTextField txtDesdeA) {
        this.txtDesdeA = txtDesdeA;
    }

    public JTextField getTxtDesdeC() {
        return txtDesdeC;
    }

    public void setTxtDesdeC(JTextField txtDesdeC) {
        this.txtDesdeC = txtDesdeC;
    }

    public JTextField getTxtDesdeE() {
        return txtDesdeE;
    }

    public void setTxtDesdeE(JTextField txtDesdeE) {
        this.txtDesdeE = txtDesdeE;
    }

    public JTextField getTxtDesdeT() {
        return txtDesdeT;
    }

    public void setTxtDesdeT(JTextField txtDesdeT) {
        this.txtDesdeT = txtDesdeT;
    }

    public JTextField getTxtHastaA() {
        return txtHastaA;
    }

    public void setTxtHastaA(JTextField txtHastaA) {
        this.txtHastaA = txtHastaA;
    }

    public JTextField getTxtHastaC() {
        return txtHastaC;
    }

    public void setTxtHastaC(JTextField txtHastaC) {
        this.txtHastaC = txtHastaC;
    }

    public JTextField getTxtHastaE() {
        return txtHastaE;
    }

    public void setTxtHastaE(JTextField txtHastaE) {
        this.txtHastaE = txtHastaE;
    }

    public JTextField getTxtHastaT() {
        return txtHastaT;
    }

    public void setTxtHastaT(JTextField txtHastaT) {
        this.txtHastaT = txtHastaT;
    }

    public JTextField getTxtLugarE() {
        return txtLugarE;
    }

    public void setTxtLugarE(JTextField txtLugarE) {
        this.txtLugarE = txtLugarE;
    }

    public JTextField getTxtPEA() {
        return txtPEA;
    }

    public void setTxtPEA(JTextField txtPEA) {
        this.txtPEA = txtPEA;
    }

    public JTextField getTxtPEC() {
        return txtPEC;
    }

    public void setTxtPEC(JTextField txtPEC) {
        this.txtPEC = txtPEC;
    }

    public JTextField getTxtPEE() {
        return txtPEE;
    }

    public void setTxtPEE(JTextField txtPEE) {
        this.txtPEE = txtPEE;
    }

    public JTextField getTxtPET() {
        return txtPET;
    }

    public void setTxtPET(JTextField txtPET) {
        this.txtPET = txtPET;
    }

    public JTextField getTxtSeguroE() {
        return txtSeguroE;
    }

    public void setTxtSeguroE(JTextField txtSeguroE) {
        this.txtSeguroE = txtSeguroE;
    }

    public JTextField getTxtSeguroT() {
        return txtSeguroT;
    }

    public void setTxtSeguroT(JTextField txtSeguroT) {
        this.txtSeguroT = txtSeguroT;
    }





}
