/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class VServicio extends javax.swing.JDialog {

    /**
     * Creates new form VServicio2
     */
    public VServicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDesdeA = new javax.swing.JTextField();
        txtHastaA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPEC = new javax.swing.JTextField();
        txtDesdeC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHastaC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtPEA = new javax.swing.JTextField();
        txtDesdeT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtHastaT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPET = new javax.swing.JTextField();
        txtSeguroT = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtDesdeE = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtHastaE = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtLugarE = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtSeguroE = new javax.swing.JTextField();
        txtPEE = new javax.swing.JTextField();
        botonACEPTAR = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Servicios - TurismoARG");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1060, 12));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 1060, 10));

        jCheckBox1.setText("Alojamiento");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jCheckBox2.setText("Comida");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jCheckBox3.setText("Transporte");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jCheckBox4.setText("Excursion");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 10, 10, 490));

        jLabel1.setText("Desde:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 39, -1, -1));

        jLabel2.setText("Hasta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 94, -1, -1));

        txtDesdeA.setEnabled(false);
        getContentPane().add(txtDesdeA, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 36, 80, -1));

        txtHastaA.setEnabled(false);
        getContentPane().add(txtHastaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 91, 80, -1));

        jLabel3.setText("Categoria:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 39, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("*");
        jRadioButton1.setEnabled(false);
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 35, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("**");
        jRadioButton2.setEnabled(false);
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 35, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("***");
        jRadioButton3.setEnabled(false);
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 35, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("****");
        jRadioButton4.setEnabled(false);
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 35, -1, -1));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("*****");
        jRadioButton5.setEnabled(false);
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 35, -1, -1));

        jLabel4.setText("Ciudad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 94, -1, -1));

        jLabel5.setText("Precio Especial:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 94, -1, -1));

        txtPEC.setEnabled(false);
        txtPEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPECActionPerformed(evt);
            }
        });
        getContentPane().add(txtPEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 205, 120, -1));

        txtDesdeC.setEnabled(false);
        getContentPane().add(txtDesdeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 152, 80, -1));

        jLabel6.setText("Desde:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 155, -1, -1));

        jLabel7.setText("Hasta:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 208, -1, -1));

        txtHastaC.setEnabled(false);
        getContentPane().add(txtHastaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 205, 80, -1));

        jLabel8.setText("Tipo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 155, -1, -1));

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("Desayuno");
        jRadioButton6.setEnabled(false);
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 151, -1, -1));

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("Almuerzo");
        jRadioButton7.setEnabled(false);
        getContentPane().add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 151, -1, -1));

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setText("Merienda");
        jRadioButton8.setEnabled(false);
        getContentPane().add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 151, -1, -1));

        buttonGroup2.add(jRadioButton9);
        jRadioButton9.setText("Cena");
        jRadioButton9.setEnabled(false);
        getContentPane().add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 151, -1, -1));

        jLabel9.setText("Precio Especial:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 208, -1, -1));

        txtPEA.setEnabled(false);
        getContentPane().add(txtPEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 91, 120, -1));

        txtDesdeT.setEnabled(false);
        getContentPane().add(txtDesdeT, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 275, 80, -1));

        jLabel10.setText("Desde:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 278, -1, -1));

        jLabel11.setText("Hasta:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 324, -1, -1));

        txtHastaT.setEnabled(false);
        getContentPane().add(txtHastaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 321, 80, -1));

        jLabel12.setText("Tipo de Vehiculo:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 278, -1, -1));

        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setText("Omnibus");
        jRadioButton10.setEnabled(false);
        getContentPane().add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 274, -1, -1));

        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setText("Avion");
        jRadioButton11.setEnabled(false);
        getContentPane().add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 274, -1, -1));

        jLabel13.setText("Comodidad:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 324, 81, -1));

        buttonGroup4.add(jRadioButton12);
        jRadioButton12.setText("Basico");
        jRadioButton12.setEnabled(false);
        getContentPane().add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 320, -1, -1));

        buttonGroup4.add(jRadioButton13);
        jRadioButton13.setText("Ejecutivo");
        jRadioButton13.setEnabled(false);
        getContentPane().add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 320, -1, -1));

        jLabel14.setText("Seguro:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 278, -1, -1));

        jLabel15.setText("Precio Especial:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 324, -1, -1));

        txtPET.setEnabled(false);
        getContentPane().add(txtPET, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 321, 120, -1));

        txtSeguroT.setEnabled(false);
        getContentPane().add(txtSeguroT, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 275, 120, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1060, 10));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 254, 1060, 10));

        txtDesdeE.setEnabled(false);
        getContentPane().add(txtDesdeE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 80, -1));

        jLabel16.setText("Desde:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, 20));

        jLabel17.setText("Hasta:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, 20));

        txtHastaE.setEnabled(false);
        getContentPane().add(txtHastaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 80, -1));

        jLabel18.setText("Lugar:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, 20));

        txtLugarE.setEnabled(false);
        getContentPane().add(txtLugarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 180, -1));

        jLabel19.setText("Precio Especial:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, -1));

        jLabel20.setText("Seguro:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, 20));

        txtSeguroE.setEnabled(false);
        getContentPane().add(txtSeguroE, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 120, -1));

        txtPEE.setEnabled(false);
        getContentPane().add(txtPEE, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 120, -1));

        botonACEPTAR.setText("ACEPTAR");
        botonACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonACEPTARActionPerformed(evt);
            }
        });
        getContentPane().add(botonACEPTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1060, 10));

        jButton3.setText("Agregar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, -1, 40));

        jButton4.setText("Agregar");
        jButton4.setEnabled(false);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, -1, 40));

        jButton5.setText("Agregar");
        jButton5.setEnabled(false);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 300, -1, 40));

        jButton6.setText("Agregar");
        jButton6.setEnabled(false);
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 420, -1, 40));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 1060, 12));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected())
        {
            jComboBox1.setEnabled(true);
            txtDesdeA.setEnabled(true);
            txtHastaA.setEnabled(true);
            txtPEA.setEnabled(true);
            jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
            jRadioButton3.setEnabled(true);
            jRadioButton4.setEnabled(true);
            jRadioButton5.setEnabled(true);
            jButton3.setEnabled(true);
        }
        else
        {
            jComboBox1.setEnabled(false);
            txtDesdeA.setEnabled(false);
            txtHastaA.setEnabled(false);
            txtPEA.setEnabled(false);
            jRadioButton1.setEnabled(false);
            jRadioButton2.setEnabled(false);
            jRadioButton3.setEnabled(false);
            jRadioButton4.setEnabled(false);
            jRadioButton5.setEnabled(false);
            jButton3.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txtPECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPECActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPECActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(jCheckBox2.isSelected())
        {
            
            txtDesdeC.setEnabled(true);
            txtHastaC.setEnabled(true);
            txtPEC.setEnabled(true);
            jRadioButton6.setEnabled(true);
            jRadioButton7.setEnabled(true);
            jRadioButton8.setEnabled(true);
            jRadioButton9.setEnabled(true);
            
            
        }
        else
        {
            txtDesdeC.setEnabled(false);
            txtHastaC.setEnabled(false);
            txtPEC.setEnabled(false);
            jRadioButton6.setEnabled(false);
            jRadioButton7.setEnabled(false);
            jRadioButton8.setEnabled(false);
            jRadioButton9.setEnabled(false);
            
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if(jCheckBox3.isSelected())
        {
            
            txtDesdeT.setEnabled(true);
            txtHastaT.setEnabled(true);
            txtPET.setEnabled(true);
            jRadioButton10.setEnabled(true);
            jRadioButton11.setEnabled(true);
            jRadioButton12.setEnabled(true);
            jRadioButton13.setEnabled(true);
            txtSeguroT.setEnabled(true);
            
        }
        else
        {
            txtDesdeT.setEnabled(false);
            txtHastaT.setEnabled(false);
            txtPET.setEnabled(false);
            jRadioButton10.setEnabled(false);
            jRadioButton11.setEnabled(false);
            jRadioButton12.setEnabled(false);
            jRadioButton13.setEnabled(false);
            txtSeguroT.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
       if(jCheckBox4.isSelected())
        {
            
            txtDesdeE.setEnabled(true);
            txtHastaE.setEnabled(true);
            txtPEE.setEnabled(true);
            txtLugarE.setEnabled(true);
            txtSeguroE.setEnabled(true);
            
        }
        else
        {
            txtDesdeE.setEnabled(false);
            txtHastaE.setEnabled(false);
            txtPEE.setEnabled(false);
            txtLugarE.setEnabled(false);
            txtSeguroE.setEnabled(false);
            
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void botonACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonACEPTARActionPerformed
        controlador.ControladorServicio.cerrar();
    }//GEN-LAST:event_botonACEPTARActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        controlador.ControladorServicio.agregarAlojamiento();
        jComboBox1.setEnabled(false);
            txtDesdeA.setEnabled(false);
            txtDesdeA.setText("");
            txtHastaA.setEnabled(false);
            txtHastaA.setText("");
            txtPEA.setEnabled(false);
            txtPEA.setText("");
            jRadioButton1.setEnabled(false);
            jRadioButton2.setEnabled(false);
            jRadioButton3.setEnabled(false);
            jRadioButton4.setEnabled(false);
            jRadioButton5.setEnabled(false);
            jButton3.setEnabled(false);
            jCheckBox1.setSelected(false);
            
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        //java.awt.EventQueue.invokeLater(new Runnable() {
          //  public void run() {
          //      VServicio2 dialog = new VServicio2(new javax.swing.JFrame(), true);
           //     dialog.addWindowListener(new java.awt.event.WindowAdapter() {
           //         @Override
          //          public void windowClosing(java.awt.event.WindowEvent e) {
           //             System.exit(0);
           //         }
           //     });
          //      dialog.setVisible(true);
        //    }
      //  });
        //</editor-fold>

        /* Create and display the dialog */
        //java.awt.EventQueue.invokeLater(new Runnable() {
          //  public void run() {
          //      VServicio dialog = new VServicio(new javax.swing.JFrame(), true);
           //     dialog.addWindowListener(new java.awt.event.WindowAdapter() {
           //         @Override
          //          public void windowClosing(java.awt.event.WindowEvent e) {
           //             System.exit(0);
           //         }
           //     });
          //      dialog.setVisible(true);
        //    }
      //  });
      
    }

    public JRadioButton getjRadioButton1() {
        return jRadioButton1;
    }

    public void setjRadioButton1(JRadioButton jRadioButton1) {
        this.jRadioButton1 = jRadioButton1;
    }

    public JRadioButton getjRadioButton10() {
        return jRadioButton10;
    }

    public void setjRadioButton10(JRadioButton jRadioButton10) {
        this.jRadioButton10 = jRadioButton10;
    }

    public JRadioButton getjRadioButton11() {
        return jRadioButton11;
    }

    public void setjRadioButton11(JRadioButton jRadioButton11) {
        this.jRadioButton11 = jRadioButton11;
    }

    public JRadioButton getjRadioButton12() {
        return jRadioButton12;
    }

    public void setjRadioButton12(JRadioButton jRadioButton12) {
        this.jRadioButton12 = jRadioButton12;
    }

    public JRadioButton getjRadioButton13() {
        return jRadioButton13;
    }

    public void setjRadioButton13(JRadioButton jRadioButton13) {
        this.jRadioButton13 = jRadioButton13;
    }

    public JRadioButton getjRadioButton2() {
        return jRadioButton2;
    }

    public void setjRadioButton2(JRadioButton jRadioButton2) {
        this.jRadioButton2 = jRadioButton2;
    }

    public JRadioButton getjRadioButton3() {
        return jRadioButton3;
    }

    public void setjRadioButton3(JRadioButton jRadioButton3) {
        this.jRadioButton3 = jRadioButton3;
    }

    public JRadioButton getjRadioButton4() {
        return jRadioButton4;
    }

    public void setjRadioButton4(JRadioButton jRadioButton4) {
        this.jRadioButton4 = jRadioButton4;
    }

    public JRadioButton getjRadioButton5() {
        return jRadioButton5;
    }

    public void setjRadioButton5(JRadioButton jRadioButton5) {
        this.jRadioButton5 = jRadioButton5;
    }

    public JRadioButton getjRadioButton6() {
        return jRadioButton6;
    }

    public void setjRadioButton6(JRadioButton jRadioButton6) {
        this.jRadioButton6 = jRadioButton6;
    }

    public JRadioButton getjRadioButton7() {
        return jRadioButton7;
    }

    public void setjRadioButton7(JRadioButton jRadioButton7) {
        this.jRadioButton7 = jRadioButton7;
    }

    public JRadioButton getjRadioButton8() {
        return jRadioButton8;
    }

    public void setjRadioButton8(JRadioButton jRadioButton8) {
        this.jRadioButton8 = jRadioButton8;
    }

    public JRadioButton getjRadioButton9() {
        return jRadioButton9;
    }

    public void setjRadioButton9(JRadioButton jRadioButton9) {
        this.jRadioButton9 = jRadioButton9;
    }

     public JTextField getTxtDesdeA() {
        return txtDesdeA;
    }

    public void setTxtDesdeA(JTextField txtDesdeA) {
        this.txtDesdeA = txtDesdeA;
    }

    public JTextField getTxtDesdeC() {
        return txtDesdeT;
    }

    public void setTxtDesdeC(JTextField txtDesdeC) {
        this.txtDesdeT = txtDesdeC;
    }

    public JTextField getTxtDesdeE() {
        return txtDesdeE;
    }

    public void setTxtDesdeE(JTextField txtDesdeE) {
        this.txtDesdeE = txtDesdeE;
    }

    public JTextField getTxtDesdeT() {
        return txtDesdeC;
    }

    public void setTxtDesdeT(JTextField txtDesdeT) {
        this.txtDesdeC = txtDesdeT;
    }

    public JTextField getTxtHastaA() {
        return txtHastaA;
    }

    public void setTxtHastaA(JTextField txtHastaA) {
        this.txtHastaA = txtHastaA;
    }

    public JTextField getTxtHastaC() {
        return txtHastaT;
    }

    public void setTxtHastaC(JTextField txtHastaC) {
        this.txtHastaT = txtHastaC;
    }

    public JTextField getTxtHastaE() {
        return txtHastaE;
    }

    public void setTxtHastaE(JTextField txtHastaE) {
        this.txtHastaE = txtHastaE;
    }

    public JTextField getTxtHastaT() {
        return txtHastaC;
    }

    public void setTxtHastaT(JTextField txtHastaT) {
        this.txtHastaC = txtHastaT;
    }

    public JTextField getTxtLugarE() {
        return txtLugarE;
    }

    public void setTxtLugarE(JTextField txtLugarE) {
        this.txtLugarE = txtLugarE;
    }

    public JTextField getTxtPEA() {
        return txtPEA;
    }

    public void setTxtPEA(JTextField txtPEA) {
        this.txtPEA = txtPEA;
    }

    public JTextField getTxtPEC() {
        return txtPET;
    }

    public void setTxtPEC(JTextField txtPEC) {
        this.txtPET = txtPEC;
    }

    public JTextField getTxtPEE() {
        return txtPEE;
    }

    public void setTxtPEE(JTextField txtPEE) {
        this.txtPEE = txtPEE;
    }

    public JTextField getTxtPET() {
        return txtPEC;
    }

    public void setTxtPET(JTextField txtPET) {
        this.txtPEC = txtPET;
    }

    public JTextField getTxtSeguroC() {
        return txtSeguroT;
    }

    public void setTxtSeguroC(JTextField txtSeguroC) {
        this.txtSeguroT = txtSeguroC;
    }

    public JTextField getTxtSeguroE() {
        return txtSeguroE;
    }

    public void setTxtSeguroE(JTextField txtSeguroE) {
        this.txtSeguroE = txtSeguroE;
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonACEPTAR;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField txtDesdeA;
    private javax.swing.JTextField txtDesdeC;
    private javax.swing.JTextField txtDesdeE;
    private javax.swing.JTextField txtDesdeT;
    private javax.swing.JTextField txtHastaA;
    private javax.swing.JTextField txtHastaC;
    private javax.swing.JTextField txtHastaE;
    private javax.swing.JTextField txtHastaT;
    private javax.swing.JTextField txtLugarE;
    private javax.swing.JTextField txtPEA;
    private javax.swing.JTextField txtPEC;
    private javax.swing.JTextField txtPEE;
    private javax.swing.JTextField txtPET;
    private javax.swing.JTextField txtSeguroE;
    private javax.swing.JTextField txtSeguroT;
    // End of variables declaration//GEN-END:variables
}
